package net.streamdek.mobile.nativeapp

/** Local keys for every cloud field. Used for durable retry, conflict protection and audit coverage. */
internal object SettingsSyncRegistry {
  val keysByField: Map<String, Set<String>> = linkedMapOf(
    "favoriteSourceKeys" to setOf("favorite_source_keys"),
    "appAppearance" to setOf("app_appearance"),
    "themePreset" to setOf("theme_preset"),
    "headerStyle" to setOf("header_style"),
    "showNavLabels" to setOf("show_nav_labels"),
    "collapsibleNavigationEnabled" to setOf("collapsible_navigation_enabled"),
    "navigationAutoCollapseSeconds" to setOf("navigation_auto_collapse_seconds"),
    "syncOnCellular" to setOf("sync_on_cellular"),
    "detailPageStyle" to setOf("detail_page_style"),
    "continueWatchingStyle" to setOf("continue_watching_style"),
    "homeCardTextMode" to setOf("home_card_text_mode"),
    "networkCardStyle" to setOf("network_card_style"),
    "liveLandscapeCards" to setOf("live_landscape_cards"),
    "liveFavouriteDrawerCards" to setOf("live_favourite_drawer_cards"),
    "liveCategoriesEnabled" to setOf("live_categories_enabled"),
    "primarySyncService" to setOf("primary_sync_service"),
    "showHeroSynopsis" to setOf("show_hero_synopsis"),
    "vividAmbient" to setOf("vivid_ambient"),
    "ambientTintPercent" to setOf("ambient_tint_percent"),
    "detailAmbientTintPercent" to setOf("detail_ambient_tint_percent"),
    "defaultAppCatalogsEnabled" to setOf("default_app_catalogs_enabled"),
    "homeCatalogRowsJson" to setOf("home_catalog_rows"),
    "homeRowMode" to setOf("home_row_mode"),
    "homeRowSourceOrder" to setOf("home_row_source_order"),
    "seasonTabStyle" to setOf("season_tab_style"),
    "episodeLayout" to setOf("episode_layout"),
    "heroTrailerAutoplay" to setOf("hero_trailer_autoplay"),
    "heroTrailerResolution" to setOf("hero_trailer_resolution"),
    "heroTrailerDelaySeconds" to setOf("hero_trailer_delay_seconds"),
    "trailerCacheClearHours" to setOf("trailer_cache_clear_hours"),
    "detailBackgroundMode" to setOf("detail_background_mode"),
    "homeBackgroundMode" to setOf("home_background_mode"),
    "secondaryAudioLanguage" to setOf("secondary_audio_language"),
    "preferredSubtitleLanguage" to setOf("preferred_subtitle_language"),
    "secondarySubtitleLanguage" to setOf("secondary_subtitle_language"),
    "useForcedSubtitles" to setOf("use_forced_subtitles"),
    "showOnlyPreferredSubtitleLanguages" to setOf("show_only_preferred_subtitle_languages"),
    "addonSubtitleLoading" to setOf("addon_subtitle_loading"),
    "subtitleDefaultSource" to setOf("subtitle_default_source"),
    "liveProgressBarEnabled" to setOf("live_progress_bar"),
    "liveBadgeEnabled" to setOf("live_badge"),
    "subtitleTextSize" to setOf("subtitle_text_size"),
    "subtitleVerticalOffset" to setOf("subtitle_vertical_offset"),
    "subtitleBold" to setOf("subtitle_bold"),
    "subtitleTextColor" to setOf("subtitle_text_color"),
    "subtitleBackgroundColor" to setOf("subtitle_background_color"),
    "subtitleOutline" to setOf("subtitle_outline"),
    "subtitleOutlineColor" to setOf("subtitle_outline_color"),
    "showNewEpisodesRow" to setOf("show_new_episodes_row"),
    "newEpisodesLandscape" to setOf("new_episodes_landscape"),
    "plexContinueWatchingLocation" to setOf("plex_continue_watching_location"),
    "jellyfinContinueWatchingLocation" to setOf("jellyfin_continue_watching_location"),
    "animationSpeed" to setOf("animation_speed"),
    "appLanguage" to setOf("app_language"),
    "visualEffects" to setOf("visual_effects"),
    "navigationBehaviour" to setOf("collapsible_navigation_enabled", "navigation_collapse_trigger", "navigation_expanded_headers"),
    "homeDensity" to setOf("home_density"),
    "mediaHubEnabled" to setOf("media_hub_enabled"),
    "heroTrailerMuted" to setOf("hero_trailer_muted"),
    "playerControlLayout" to setOf("player_control_layout"),
    "showPlayerControlLabels" to setOf("show_player_control_labels"),
    "playerTitleDisplay" to setOf("player_title_display"),
    "fullscreenStatusBar" to setOf("fullscreen_status_bar"),
    "holdToSpeedEnabled" to setOf("hold_to_speed_enabled"),
    "holdToSpeedMultiplier" to setOf("hold_to_speed_multiplier"),
    "swipeToSeekEnabled" to setOf("swipe_to_seek_enabled"),
    "doubleTapSeekEnabled" to setOf("double_tap_seek_enabled"),
    "doubleTapSeekSeconds" to setOf("double_tap_seek_seconds"),
    "doubleTapPlayPauseEnabled" to setOf("double_tap_play_pause_enabled"),
    "playerLevelGesturesEnabled" to setOf("player_level_gestures_enabled"),
    "ratingsEnabled" to setOf("ratings_enabled"),
    "externalRatingsEnabled" to setOf("external_ratings_enabled"),
    "enabledRatingProviders" to setOf("enabled_rating_providers"),
    "mdblistApiKey" to setOf(),
    "pictureInPictureEnabled" to setOf("pip_enabled"),
    "decoderMode" to setOf("decoder_mode"),
    "renderSurface" to setOf("render_surface"),
    "playerEngine" to setOf("player_engine"),
    "preferredAudioLanguage" to setOf("preferred_audio_language"),
    "introdbApiKey" to setOf(),
    "skipIntroEnabled" to setOf("skip_intro_enabled", "skip_segments_enabled"),
    "skipRecapEnabled" to setOf("skip_recap_enabled"),
    "skipEndingEnabled" to setOf("skip_ending_enabled"),
    "autoSkipIntroEnabled" to setOf("auto_skip_intro_enabled"),
    "autoSkipRecapEnabled" to setOf("auto_skip_recap_enabled"),
    "autoSkipEndingEnabled" to setOf("auto_skip_ending_enabled"),
    "autoPlayNextEpisode" to setOf("auto_play_next_episode"),
    "preferBingeGroup" to setOf("prefer_binge_group"),
    "autoLoadSubtitles" to setOf("auto_load_subtitles"),
    "nextEpisodeThresholdMode" to setOf("next_episode_threshold_mode"),
    "nextEpisodeThresholdPercent" to setOf("next_episode_threshold_percent"),
    "nextEpisodeThresholdMinutes" to setOf("next_episode_threshold_minutes"),
    "endOfPlaybackRecommendationsEnabled" to setOf("end_of_playback_recommendations_enabled"),
    "recommendationTiming" to setOf("recommendation_timing"),
    "recommendationItemCount" to setOf("recommendation_item_count"),
    "timingProvider" to setOf("timing_provider"),
    "timingProviderFallbackEnabled" to setOf("timing_provider_fallback_enabled"),
    "showStreamsList" to setOf("show_streams_list"),
    "rememberLastSource" to setOf("remember_last_source"),
    "blurUnwatchedEpisodes" to setOf("blur_unwatched_episodes"),
    "fusionBadgesEnabled" to setOf("fusion_badges"),
    "streamDekFormattingEnabled" to setOf("streamdek_stream_formatting"),
    "showSizeBadges" to setOf("show_size_badges"),
    "preferredQuality" to setOf("preferred_quality"),
    "maxFileSizeGb" to setOf("max_file_size_gb"),
    "badgePosition" to setOf("badge_position"),
    "fusionBadgeUrls" to setOf("fusion_badge_urls", "active_fusion_badge_url"),
    "activeFusionBadgeUrl" to setOf("fusion_badge_urls", "active_fusion_badge_url"),
    "autoUpdateChecksEnabled" to setOf("auto_update_checks"),
  )
  val syncedKeys: Set<String> = keysByField.values.flatten().toSet()

  /** Composite controls must be protected as a unit (navigation mode, badge list/selection). */
  fun protectedKeys(pending: Set<String>): Set<String> {
    val protected = pending.toMutableSet()
    do {
      val count = protected.size
      keysByField.values.filter { keys -> keys.any { it in protected } }.forEach(protected::addAll)
    } while (protected.size != count)
    return protected
  }

  fun select(value: CloudPlaybackPreferences, keys: Set<String>): CloudPlaybackPreferences {
    fun keep(field: String) = keysByField.getValue(field).any { it in keys }
    return value.copy(
      favoriteSourceKeys = if (keep("favoriteSourceKeys")) value.favoriteSourceKeys else null,
      appAppearance = if (keep("appAppearance")) value.appAppearance else null,
      themePreset = if (keep("themePreset")) value.themePreset else null,
      headerStyle = if (keep("headerStyle")) value.headerStyle else null,
      showNavLabels = if (keep("showNavLabels")) value.showNavLabels else null,
      collapsibleNavigationEnabled = if (keep("collapsibleNavigationEnabled")) value.collapsibleNavigationEnabled else null,
      navigationAutoCollapseSeconds = if (keep("navigationAutoCollapseSeconds")) value.navigationAutoCollapseSeconds else null,
      syncOnCellular = if (keep("syncOnCellular")) value.syncOnCellular else null,
      detailPageStyle = if (keep("detailPageStyle")) value.detailPageStyle else null,
      continueWatchingStyle = if (keep("continueWatchingStyle")) value.continueWatchingStyle else null,
      homeCardTextMode = if (keep("homeCardTextMode")) value.homeCardTextMode else null,
      networkCardStyle = if (keep("networkCardStyle")) value.networkCardStyle else null,
      liveLandscapeCards = if (keep("liveLandscapeCards")) value.liveLandscapeCards else null,
      liveFavouriteDrawerCards = if (keep("liveFavouriteDrawerCards")) value.liveFavouriteDrawerCards else null,
      liveCategoriesEnabled = if (keep("liveCategoriesEnabled")) value.liveCategoriesEnabled else null,
      primarySyncService = if (keep("primarySyncService")) value.primarySyncService else null,
      showHeroSynopsis = if (keep("showHeroSynopsis")) value.showHeroSynopsis else null,
      vividAmbient = if (keep("vividAmbient")) value.vividAmbient else null,
      ambientTintPercent = if (keep("ambientTintPercent")) value.ambientTintPercent else null,
      detailAmbientTintPercent = if (keep("detailAmbientTintPercent")) value.detailAmbientTintPercent else null,
      defaultAppCatalogsEnabled = if (keep("defaultAppCatalogsEnabled")) value.defaultAppCatalogsEnabled else null,
      homeCatalogRowsJson = if (keep("homeCatalogRowsJson")) value.homeCatalogRowsJson else null,
      homeRowMode = if (keep("homeRowMode")) value.homeRowMode else null,
      homeRowSourceOrder = if (keep("homeRowSourceOrder")) value.homeRowSourceOrder else null,
      seasonTabStyle = if (keep("seasonTabStyle")) value.seasonTabStyle else null,
      episodeLayout = if (keep("episodeLayout")) value.episodeLayout else null,
      heroTrailerAutoplay = if (keep("heroTrailerAutoplay")) value.heroTrailerAutoplay else null,
      heroTrailerResolution = if (keep("heroTrailerResolution")) value.heroTrailerResolution else null,
      heroTrailerDelaySeconds = if (keep("heroTrailerDelaySeconds")) value.heroTrailerDelaySeconds else null,
      trailerCacheClearHours = if (keep("trailerCacheClearHours")) value.trailerCacheClearHours else null,
      detailBackgroundMode = if (keep("detailBackgroundMode")) value.detailBackgroundMode else null,
      homeBackgroundMode = if (keep("homeBackgroundMode")) value.homeBackgroundMode else null,
      secondaryAudioLanguage = if (keep("secondaryAudioLanguage")) value.secondaryAudioLanguage else null,
      preferredSubtitleLanguage = if (keep("preferredSubtitleLanguage")) value.preferredSubtitleLanguage else null,
      secondarySubtitleLanguage = if (keep("secondarySubtitleLanguage")) value.secondarySubtitleLanguage else null,
      useForcedSubtitles = if (keep("useForcedSubtitles")) value.useForcedSubtitles else null,
      showOnlyPreferredSubtitleLanguages = if (keep("showOnlyPreferredSubtitleLanguages")) value.showOnlyPreferredSubtitleLanguages else null,
      addonSubtitleLoading = if (keep("addonSubtitleLoading")) value.addonSubtitleLoading else null,
      subtitleDefaultSource = if (keep("subtitleDefaultSource")) value.subtitleDefaultSource else null,
      liveProgressBarEnabled = if (keep("liveProgressBarEnabled")) value.liveProgressBarEnabled else null,
      liveBadgeEnabled = if (keep("liveBadgeEnabled")) value.liveBadgeEnabled else null,
      subtitleTextSize = if (keep("subtitleTextSize")) value.subtitleTextSize else null,
      subtitleVerticalOffset = if (keep("subtitleVerticalOffset")) value.subtitleVerticalOffset else null,
      subtitleBold = if (keep("subtitleBold")) value.subtitleBold else null,
      subtitleTextColor = if (keep("subtitleTextColor")) value.subtitleTextColor else null,
      subtitleBackgroundColor = if (keep("subtitleBackgroundColor")) value.subtitleBackgroundColor else null,
      subtitleOutline = if (keep("subtitleOutline")) value.subtitleOutline else null,
      subtitleOutlineColor = if (keep("subtitleOutlineColor")) value.subtitleOutlineColor else null,
      showNewEpisodesRow = if (keep("showNewEpisodesRow")) value.showNewEpisodesRow else null,
      newEpisodesLandscape = if (keep("newEpisodesLandscape")) value.newEpisodesLandscape else null,
      plexContinueWatchingLocation = if (keep("plexContinueWatchingLocation")) value.plexContinueWatchingLocation else null,
      jellyfinContinueWatchingLocation = if (keep("jellyfinContinueWatchingLocation")) value.jellyfinContinueWatchingLocation else null,
      animationSpeed = if (keep("animationSpeed")) value.animationSpeed else null,
      appLanguage = if (keep("appLanguage")) value.appLanguage else null,
      visualEffects = if (keep("visualEffects")) value.visualEffects else null,
      navigationBehaviour = if (keep("navigationBehaviour")) value.navigationBehaviour else null,
      homeDensity = if (keep("homeDensity")) value.homeDensity else null,
      mediaHubEnabled = if (keep("mediaHubEnabled")) value.mediaHubEnabled else null,
      heroTrailerMuted = if (keep("heroTrailerMuted")) value.heroTrailerMuted else null,
      playerControlLayout = if (keep("playerControlLayout")) value.playerControlLayout else null,
      showPlayerControlLabels = if (keep("showPlayerControlLabels")) value.showPlayerControlLabels else null,
      playerTitleDisplay = if (keep("playerTitleDisplay")) value.playerTitleDisplay else null,
      fullscreenStatusBar = if (keep("fullscreenStatusBar")) value.fullscreenStatusBar else null,
      holdToSpeedEnabled = if (keep("holdToSpeedEnabled")) value.holdToSpeedEnabled else null,
      holdToSpeedMultiplier = if (keep("holdToSpeedMultiplier")) value.holdToSpeedMultiplier else null,
      swipeToSeekEnabled = if (keep("swipeToSeekEnabled")) value.swipeToSeekEnabled else null,
      doubleTapSeekEnabled = if (keep("doubleTapSeekEnabled")) value.doubleTapSeekEnabled else null,
      doubleTapSeekSeconds = if (keep("doubleTapSeekSeconds")) value.doubleTapSeekSeconds else null,
      doubleTapPlayPauseEnabled = if (keep("doubleTapPlayPauseEnabled")) value.doubleTapPlayPauseEnabled else null,
      playerLevelGesturesEnabled = if (keep("playerLevelGesturesEnabled")) value.playerLevelGesturesEnabled else null,
      ratingsEnabled = if (keep("ratingsEnabled")) value.ratingsEnabled else null,
      externalRatingsEnabled = if (keep("externalRatingsEnabled")) value.externalRatingsEnabled else null,
      enabledRatingProviders = if (keep("enabledRatingProviders")) value.enabledRatingProviders else null,
      mdblistApiKey = if (keep("mdblistApiKey")) value.mdblistApiKey else null,
      pictureInPictureEnabled = if (keep("pictureInPictureEnabled")) value.pictureInPictureEnabled else null,
      decoderMode = if (keep("decoderMode")) value.decoderMode else null,
      renderSurface = if (keep("renderSurface")) value.renderSurface else null,
      playerEngine = if (keep("playerEngine")) value.playerEngine else null,
      preferredAudioLanguage = if (keep("preferredAudioLanguage")) value.preferredAudioLanguage else null,
      introdbApiKey = if (keep("introdbApiKey")) value.introdbApiKey else null,
      skipIntroEnabled = if (keep("skipIntroEnabled")) value.skipIntroEnabled else null,
      skipRecapEnabled = if (keep("skipRecapEnabled")) value.skipRecapEnabled else null,
      skipEndingEnabled = if (keep("skipEndingEnabled")) value.skipEndingEnabled else null,
      autoSkipIntroEnabled = if (keep("autoSkipIntroEnabled")) value.autoSkipIntroEnabled else null,
      autoSkipRecapEnabled = if (keep("autoSkipRecapEnabled")) value.autoSkipRecapEnabled else null,
      autoSkipEndingEnabled = if (keep("autoSkipEndingEnabled")) value.autoSkipEndingEnabled else null,
      autoPlayNextEpisode = if (keep("autoPlayNextEpisode")) value.autoPlayNextEpisode else null,
      preferBingeGroup = if (keep("preferBingeGroup")) value.preferBingeGroup else null,
      autoLoadSubtitles = if (keep("autoLoadSubtitles")) value.autoLoadSubtitles else null,
      nextEpisodeThresholdMode = if (keep("nextEpisodeThresholdMode")) value.nextEpisodeThresholdMode else null,
      nextEpisodeThresholdPercent = if (keep("nextEpisodeThresholdPercent")) value.nextEpisodeThresholdPercent else null,
      nextEpisodeThresholdMinutes = if (keep("nextEpisodeThresholdMinutes")) value.nextEpisodeThresholdMinutes else null,
      endOfPlaybackRecommendationsEnabled = if (keep("endOfPlaybackRecommendationsEnabled")) value.endOfPlaybackRecommendationsEnabled else null,
      recommendationTiming = if (keep("recommendationTiming")) value.recommendationTiming else null,
      recommendationItemCount = if (keep("recommendationItemCount")) value.recommendationItemCount else null,
      timingProvider = if (keep("timingProvider")) value.timingProvider else null,
      timingProviderFallbackEnabled = if (keep("timingProviderFallbackEnabled")) value.timingProviderFallbackEnabled else null,
      showStreamsList = if (keep("showStreamsList")) value.showStreamsList else null,
      rememberLastSource = if (keep("rememberLastSource")) value.rememberLastSource else null,
      blurUnwatchedEpisodes = if (keep("blurUnwatchedEpisodes")) value.blurUnwatchedEpisodes else null,
      fusionBadgesEnabled = if (keep("fusionBadgesEnabled")) value.fusionBadgesEnabled else null,
      streamDekFormattingEnabled = if (keep("streamDekFormattingEnabled")) value.streamDekFormattingEnabled else null,
      showSizeBadges = if (keep("showSizeBadges")) value.showSizeBadges else null,
      preferredQuality = if (keep("preferredQuality")) value.preferredQuality else null,
      maxFileSizeGb = if (keep("maxFileSizeGb")) value.maxFileSizeGb else null,
      badgePosition = if (keep("badgePosition")) value.badgePosition else null,
      fusionBadgeUrls = if (keep("fusionBadgeUrls")) value.fusionBadgeUrls else null,
      activeFusionBadgeUrl = if (keep("activeFusionBadgeUrl")) value.activeFusionBadgeUrl else null,
      autoUpdateChecksEnabled = if (keep("autoUpdateChecksEnabled")) value.autoUpdateChecksEnabled else null,
    )
  }
}
